using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class ShieldController : MonoBehaviour
{
    public float maxShield, currentShield;
    public float shieldDuration;
    public GameObject shield;
    private InputController input;
    public Text current, max;

    private void Start()
    {
        input = GetComponent<InputController>();
    }
    private void FixedUpdate()
    {
        if (input.Shield && currentShield > 0)
        {
            shield.SetActive(true);
            currentShield-=shieldDuration;
        } else
        {
            shield.SetActive(false);
        }
        current.text = Mathf.RoundToInt(currentShield).ToString();
        max.text = Mathf.RoundToInt(maxShield).ToString();
        
    }

    public void RestoreShield(float shieldPoints)
    {
        if (currentShield+shieldPoints > maxShield)
        {
            currentShield = maxShield;
        } else
        {
            currentShield += shieldPoints;
        }
    }

}
